<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="LiveMarkdown.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpTurns.Markdown.Rendering\SharpTurns.Markdown.Rendering.csproj" />
  </ItemGroup>
</Project>
